"""v7_3_improvements

Revision ID: 030352a1a566
Revises: 5e322a993677
Create Date: 2026-09-04 18:52:31.707548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030352a1a566'
down_revision: Union[str, Sequence[str], None] = 'c8c797395a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_claims', sa.Column('confidence_signals', sa.String(), nullable=True))
    op.add_column('research_claims', sa.Column('temporal_context', sa.String(), nullable=True))
    op.add_column('research_claims', sa.Column('normalized_claim_text', sa.String(), nullable=True))
    op.add_column('research_claims', sa.Column('quality_classification', sa.String(), nullable=True))
    pass
    op.add_column('research_evidence', sa.Column('evidence_quality', sa.String(), nullable=True))
    op.add_column('research_evidence', sa.Column('evidence_quality_reason', sa.String(), nullable=True))
    op.add_column('research_sources', sa.Column('is_syndicated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sources', 'is_syndicated')
    op.drop_column('research_evidence', 'evidence_quality_reason')
    op.drop_column('research_evidence', 'evidence_quality')
    pass
    op.drop_column('research_claims', 'quality_classification')
    op.drop_column('research_claims', 'normalized_claim_text')
    op.drop_column('research_claims', 'temporal_context')
    op.drop_column('research_claims', 'confidence_signals')
    # ### end Alembic commands ###


