"""add_v7_research_fields

Revision ID: 525c067dacb6
Revises: 0162601f17f9
Create Date: 2026-09-04 17:19:41.501647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525c067dacb6'
down_revision: Union[str, Sequence[str], None] = 'ecda6f67f334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED', name='researchrunstatus'), nullable=False),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.Column('stats', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_id'), 'research_runs', ['id'], unique=False)
    op.create_index(op.f('ix_research_runs_project_id'), 'research_runs', ['project_id'], unique=False)
    op.create_table('research_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', 'CONTRADICTED', 'REJECTED', name='claimstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_claims_id'), 'research_claims', ['id'], unique=False)
    op.create_index(op.f('ix_research_claims_project_id'), 'research_claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_claims_research_run_id'), 'research_claims', ['research_run_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('discovered_in_run_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('reliability_tier', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('retrieval_status', sa.Enum('PENDING', 'SUCCESS', 'HTTP_ERROR', 'TIMEOUT', 'MALFORMED', 'BLOCKED', 'NOT_FOUND', name='retrievalstatus'), nullable=False),
    sa.Column('error_info', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('content_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['discovered_in_run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_canonical_url'), 'research_sources', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_research_sources_id'), 'research_sources', ['id'], unique=False)
    op.create_index(op.f('ix_research_sources_project_id'), 'research_sources', ['project_id'], unique=False)
    op.create_table('research_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.Enum('SUPPORTING', 'CONTRADICTING', 'NEUTRAL', name='evidencetype'), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_evidence_claim_id'), 'research_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_research_evidence_id'), 'research_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_research_evidence_source_id'), 'research_evidence', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_evidence_source_id'), table_name='research_evidence')
    op.drop_index(op.f('ix_research_evidence_id'), table_name='research_evidence')
    op.drop_index(op.f('ix_research_evidence_claim_id'), table_name='research_evidence')
    op.drop_table('research_evidence')
    op.drop_index(op.f('ix_research_sources_project_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_canonical_url'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_claims_research_run_id'), table_name='research_claims')
    op.drop_index(op.f('ix_research_claims_project_id'), table_name='research_claims')
    op.drop_index(op.f('ix_research_claims_id'), table_name='research_claims')
    op.drop_table('research_claims')
    op.drop_index(op.f('ix_research_runs_project_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_id'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###

