"""Add thumbnail and published date to source asset

Revision ID: 99d6cc301534
Revises: 6a0c18412f17
Create Date: 2026-09-03 22:30:19.845483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d6cc301534'
down_revision: Union[str, None] = 'ed7317648a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_assets', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('source_assets', sa.Column('published_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_assets', 'published_date')
    op.drop_column('source_assets', 'thumbnail_url')
    # ### end Alembic commands ###
