"""Add relevance fields

Revision ID: ad92cf1c0080
Revises: 99d6cc301534
Create Date: 2026-09-03 22:46:39.168404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad92cf1c0080'
down_revision: Union[str, Sequence[str], None] = '99d6cc301534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_mappings', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('source_assets', sa.Column('is_short', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_assets', 'is_short')
    op.drop_column('asset_mappings', 'relevance_score')
    # ### end Alembic commands ###
