"""Add V8 story builder models

Revision ID: c336302139ef
Revises: 030352a1a566
Create Date: 2026-09-04 22:38:53.310627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c336302139ef'
down_revision: Union[str, Sequence[str], None] = '030352a1a566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('central_question', sa.String(), nullable=True),
    sa.Column('story_promise', sa.String(), nullable=True),
    sa.Column('emotional_arc', sa.String(), nullable=True),
    sa.Column('stats', sa.String(), nullable=True),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.Column('quality_score', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_runs_episode_id'), 'story_runs', ['episode_id'], unique=False)
    op.create_index(op.f('ix_story_runs_id'), 'story_runs', ['id'], unique=False)
    op.create_index(op.f('ix_story_runs_project_id'), 'story_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_runs_research_run_id'), 'story_runs', ['research_run_id'], unique=False)
    op.create_table('story_acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_run_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('narrative_question', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_run_id'], ['story_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_acts_id'), 'story_acts', ['id'], unique=False)
    op.create_index(op.f('ix_story_acts_story_run_id'), 'story_acts', ['story_run_id'], unique=False)
    op.create_table('story_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('event_date', sa.String(), nullable=True),
    sa.Column('date_precision', sa.String(), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_run_id'], ['story_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_events_id'), 'story_events', ['id'], unique=False)
    op.create_index(op.f('ix_story_events_story_run_id'), 'story_events', ['story_run_id'], unique=False)
    op.create_table('story_beats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_run_id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('narrative_role', sa.String(), nullable=False),
    sa.Column('emotional_state', sa.String(), nullable=True),
    sa.Column('dramatic_intensity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['story_acts.id'], ),
    sa.ForeignKeyConstraint(['story_run_id'], ['story_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_beats_id'), 'story_beats', ['id'], unique=False)
    op.create_index(op.f('ix_story_beats_story_run_id'), 'story_beats', ['story_run_id'], unique=False)
    op.create_table('story_event_claims',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['story_events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'claim_id')
    )
    op.create_table('story_beat_claims',
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['story_beats.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], ),
    sa.PrimaryKeyConstraint('beat_id', 'claim_id')
    )
    op.add_column('narration_segments', sa.Column('is_brief', sa.Integer(), nullable=True))
    op.add_column('narration_segments', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('narration_segments', sa.Column('must_communicate', sa.String(), nullable=True))
    op.add_column('narration_segments', sa.Column('must_not_claim', sa.String(), nullable=True))
    op.add_column('narration_segments', sa.Column('tone', sa.String(), nullable=True))
    op.add_column('narration_segments', sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('narration_segments', sa.Column('supporting_claims', sa.String(), nullable=True))

    op.add_column('scenes', sa.Column('story_run_id', sa.Integer(), nullable=True))
    op.add_column('scenes', sa.Column('story_beat_id', sa.Integer(), nullable=True))
    op.add_column('scenes', sa.Column('act_id', sa.Integer(), nullable=True))
    op.add_column('scenes', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('emotional_intent', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('visual_purpose', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'estimated_duration_seconds')
    op.drop_column('scenes', 'visual_purpose')
    op.drop_column('scenes', 'emotional_intent')
    op.drop_column('scenes', 'purpose')
    op.drop_column('scenes', 'act_id')
    op.drop_column('scenes', 'story_beat_id')
    op.drop_column('scenes', 'story_run_id')

    op.drop_column('narration_segments', 'supporting_claims')
    op.drop_column('narration_segments', 'estimated_duration_seconds')
    op.drop_column('narration_segments', 'tone')
    op.drop_column('narration_segments', 'must_not_claim')
    op.drop_column('narration_segments', 'must_communicate')
    op.drop_column('narration_segments', 'purpose')
    op.drop_column('narration_segments', 'is_brief')
    op.drop_table('story_beat_claims')
    op.drop_table('story_event_claims')
    op.drop_index(op.f('ix_story_beats_story_run_id'), table_name='story_beats')
    op.drop_index(op.f('ix_story_beats_id'), table_name='story_beats')
    op.drop_table('story_beats')
    op.drop_index(op.f('ix_story_events_story_run_id'), table_name='story_events')
    op.drop_index(op.f('ix_story_events_id'), table_name='story_events')
    op.drop_table('story_events')
    op.drop_index(op.f('ix_story_acts_story_run_id'), table_name='story_acts')
    op.drop_index(op.f('ix_story_acts_id'), table_name='story_acts')
    op.drop_table('story_acts')
    op.drop_index(op.f('ix_story_runs_research_run_id'), table_name='story_runs')
    op.drop_index(op.f('ix_story_runs_project_id'), table_name='story_runs')
    op.drop_index(op.f('ix_story_runs_id'), table_name='story_runs')
    op.drop_index(op.f('ix_story_runs_episode_id'), table_name='story_runs')
    op.drop_table('story_runs')
    # ### end Alembic commands ###

