"""v7_2_improvements

Revision ID: c8c797395a6c
Revises: baac09d73fb3
Create Date: 2026-09-04 17:51:33.730826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c797395a6c'
down_revision: Union[str, Sequence[str], None] = '525c067dacb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('research_claims', sa.Column('confidence_reason', sa.String(), nullable=True))
    op.add_column('research_sources', sa.Column('scope', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sources', 'scope')
    op.drop_column('research_claims', 'confidence_reason')
    op.drop_column('projects', 'topic')
    # ### end Alembic commands ###

