"""Initial migration

Revision ID: da3c6cb48ee2
Revises: 
Create Date: 2026-09-03 22:05:22.076802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3c6cb48ee2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_table('source_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_platform', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_duration', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('local_file_path', sa.String(), nullable=True),
    sa.Column('local_file_hash', sa.String(), nullable=True),
    sa.Column('copyright_status', sa.Enum('OFFICIAL_PUBLIC', 'USER_OWNED', 'LICENSED', 'FAIR_USE_CANDIDATE', 'UNKNOWN', 'UNSUITABLE', name='copyrightstatus'), nullable=False),
    sa.Column('usage_notes', sa.String(), nullable=True),
    sa.Column('copyright_notes', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_assets_id'), 'source_assets', ['id'], unique=False)
    op.create_index(op.f('ix_source_assets_source_url'), 'source_assets', ['source_url'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_channel_id'), 'projects', ['channel_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_project_id'), 'episodes', ['project_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_episode_id'), 'scenes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_scenes_id'), 'scenes', ['id'], unique=False)
    op.create_table('narration_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narration_segments_id'), 'narration_segments', ['id'], unique=False)
    op.create_index(op.f('ix_narration_segments_scene_id'), 'narration_segments', ['scene_id'], unique=False)
    op.create_table('visual_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narration_segment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['narration_segment_id'], ['narration_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_intents_id'), 'visual_intents', ['id'], unique=False)
    op.create_index(op.f('ix_visual_intents_narration_segment_id'), 'visual_intents', ['narration_segment_id'], unique=False)
    op.create_table('asset_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_intent_id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.Float(), nullable=True),
    sa.Column('end_timestamp', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('DISCOVERED', 'CANDIDATE', 'SELECTED', 'VERIFIED', 'APPROVED_FOR_ACQUISITION', 'DOWNLOADED', 'CLIPPED', 'READY', 'REJECTED', name='assetstate'), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ),
    sa.ForeignKeyConstraint(['visual_intent_id'], ['visual_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_mappings_id'), 'asset_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_asset_mappings_source_asset_id'), 'asset_mappings', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_mappings_visual_intent_id'), 'asset_mappings', ['visual_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_mappings_visual_intent_id'), table_name='asset_mappings')
    op.drop_index(op.f('ix_asset_mappings_source_asset_id'), table_name='asset_mappings')
    op.drop_index(op.f('ix_asset_mappings_id'), table_name='asset_mappings')
    op.drop_table('asset_mappings')
    op.drop_index(op.f('ix_visual_intents_narration_segment_id'), table_name='visual_intents')
    op.drop_index(op.f('ix_visual_intents_id'), table_name='visual_intents')
    op.drop_table('visual_intents')
    op.drop_index(op.f('ix_narration_segments_scene_id'), table_name='narration_segments')
    op.drop_index(op.f('ix_narration_segments_id'), table_name='narration_segments')
    op.drop_table('narration_segments')
    op.drop_index(op.f('ix_scenes_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_episode_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_episodes_project_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_channel_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_source_assets_source_url'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_id'), table_name='source_assets')
    op.drop_table('source_assets')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
