"""add_v6_selection_fields

Revision ID: ecda6f67f334
Revises: 5deb5a7897f9
Create Date: 2026-09-04 02:38:46.296381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecda6f67f334'
down_revision: Union[str, Sequence[str], None] = '5deb5a7897f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_mappings', sa.Column('selection_score', sa.Float(), nullable=True))
    op.add_column('asset_mappings', sa.Column('selection_reason', sa.String(), nullable=True))
    op.add_column('asset_mappings', sa.Column('confidence_level', sa.String(), nullable=True))
    op.add_column('asset_mappings', sa.Column('selection_status', sa.Enum('UNSCORED', 'AUTO_SELECTED', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', name='selectionstatus'), server_default='UNSCORED', nullable=False))
    op.add_column('asset_mappings', sa.Column('timestamp_confidence', sa.String(), nullable=True))
    op.add_column('asset_mappings', sa.Column('timestamp_reason', sa.String(), nullable=True))
    op.add_column('visual_intents', sa.Column('preferred_content_types', sa.String(), nullable=True))
    op.add_column('visual_intents', sa.Column('avoid_content_types', sa.String(), nullable=True))
    op.add_column('visual_intents', sa.Column('preferred_channels', sa.String(), nullable=True))
    op.add_column('visual_intents', sa.Column('preferred_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_intents', 'preferred_year')
    op.drop_column('visual_intents', 'preferred_channels')
    op.drop_column('visual_intents', 'avoid_content_types')
    op.drop_column('visual_intents', 'preferred_content_types')
    op.drop_column('asset_mappings', 'timestamp_reason')
    op.drop_column('asset_mappings', 'timestamp_confidence')
    op.drop_column('asset_mappings', 'selection_status')
    op.drop_column('asset_mappings', 'confidence_level')
    op.drop_column('asset_mappings', 'selection_reason')
    op.drop_column('asset_mappings', 'selection_score')
    # ### end Alembic commands ###
