"""Add missing indexes

Revision ID: ed7317648a3a
Revises: da3c6cb48ee2
Create Date: 2026-09-03 22:06:58.755114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7317648a3a'
down_revision: Union[str, Sequence[str], None] = 'da3c6cb48ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_asset_mappings_source_asset_id'), 'asset_mappings', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_mappings_visual_intent_id'), 'asset_mappings', ['visual_intent_id'], unique=False)
    op.create_index(op.f('ix_episodes_project_id'), 'episodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_narration_segments_scene_id'), 'narration_segments', ['scene_id'], unique=False)
    op.create_index(op.f('ix_projects_channel_id'), 'projects', ['channel_id'], unique=False)
    op.create_index(op.f('ix_scenes_episode_id'), 'scenes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_visual_intents_narration_segment_id'), 'visual_intents', ['narration_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_intents_narration_segment_id'), table_name='visual_intents')
    op.drop_index(op.f('ix_scenes_episode_id'), table_name='scenes')
    op.drop_index(op.f('ix_projects_channel_id'), table_name='projects')
    op.drop_index(op.f('ix_narration_segments_scene_id'), table_name='narration_segments')
    op.drop_index(op.f('ix_episodes_project_id'), table_name='episodes')
    op.drop_index(op.f('ix_asset_mappings_visual_intent_id'), table_name='asset_mappings')
    op.drop_index(op.f('ix_asset_mappings_source_asset_id'), table_name='asset_mappings')
    # ### end Alembic commands ###
