import enum

class AssetState(str, enum.Enum):
    DISCOVERED = "DISCOVERED"
    CANDIDATE = "CANDIDATE"
    SELECTED = "SELECTED"
    VERIFIED = "VERIFIED"
    APPROVED_FOR_ACQUISITION = "APPROVED_FOR_ACQUISITION"
    DOWNLOADED = "DOWNLOADED"
    CLIPPED = "CLIPPED"
    READY = "READY"
    REJECTED = "REJECTED"

class CopyrightStatus(str, enum.Enum):
    OFFICIAL_PUBLIC = "OFFICIAL_PUBLIC"
    USER_OWNED = "USER_OWNED"
    LICENSED = "LICENSED"
    FAIR_USE_CANDIDATE = "FAIR_USE_CANDIDATE"
    UNKNOWN = "UNKNOWN"
    UNSUITABLE = "UNSUITABLE"
