import enum

class AssetState(str, enum.Enum):
    DISCOVERED = "DISCOVERED"
    CANDIDATE = "CANDIDATE"
    SELECTED = "SELECTED"
    VERIFIED = "VERIFIED"
    APPROVED_FOR_ACQUISITION = "APPROVED_FOR_ACQUISITION"
    DOWNLOADED = "DOWNLOADED"
    CLIPPED = "CLIPPED"
    READY = "READY"
    REJECTED = "REJECTED"

class CopyrightStatus(str, enum.Enum):
    OFFICIAL_PUBLIC = "OFFICIAL_PUBLIC"
    USER_OWNED = "USER_OWNED"
    LICENSED = "LICENSED"
    FAIR_USE_CANDIDATE = "FAIR_USE_CANDIDATE"
    UNKNOWN = "UNKNOWN"
    UNSUITABLE = "UNSUITABLE"

class SelectionStatus(str, enum.Enum):
    UNSCORED = "UNSCORED"
    AUTO_SELECTED = "AUTO_SELECTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class ResearchRunStatus(str, enum.Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"

class RetrievalStatus(str, enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    HTTP_ERROR = "HTTP_ERROR"
    TIMEOUT = "TIMEOUT"
    MALFORMED = "MALFORMED"
    BLOCKED = "BLOCKED"
    NOT_FOUND = "NOT_FOUND"

class ClaimStatus(str, enum.Enum):
    UNVERIFIED = "UNVERIFIED"
    SINGLE_SOURCE = "SINGLE_SOURCE"
    CORROBORATED = "CORROBORATED"
    CONFLICTED = "CONFLICTED"
    REJECTED = "REJECTED"

class EvidenceType(str, enum.Enum):
    SUPPORTING = "SUPPORTING"
    CONTRADICTING = "CONTRADICTING"
    NEUTRAL = "NEUTRAL"

class StoryRunStatus(str, enum.Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class DatePrecision(str, enum.Enum):
    EXACT_DATE = "EXACT_DATE"
    MONTH = "MONTH"
    YEAR = "YEAR"
    DATE_RANGE = "DATE_RANGE"
    RELATIVE = "RELATIVE"
    UNKNOWN = "UNKNOWN"

class NarrativeRole(str, enum.Enum):
    HOOK = "HOOK"
    SETUP = "SETUP"
    CONTEXT = "CONTEXT"
    RISING_TENSION = "RISING_TENSION"
    TURNING_POINT = "TURNING_POINT"
    CRISIS = "CRISIS"
    FALLOUT = "FALLOUT"
    LOW_POINT = "LOW_POINT"
    DISCOVERY = "DISCOVERY"
    TRANSFORMATION = "TRANSFORMATION"
    PAYOFF = "PAYOFF"
    REFLECTION = "REFLECTION"
    CONCLUSION = "CONCLUSION"

class ScriptRunStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class SentenceType(str, enum.Enum):
    FACTUAL = "FACTUAL"
    TRANSITION = "TRANSITION"
    RHETORICAL = "RHETORICAL"
    DESCRIPTIVE = "DESCRIPTIVE"
    EDITORIAL = "EDITORIAL"

class ReviewStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
